rm -rf cmake_install.cmake 
rm -rf CMakeCache.txt   
rm -rf Makefile
rm -rf build
rm -rf CMakeFiles/
rm -rf .vscode
rm -rf configfs/CMakeFiles
rm -rf configfs/cmake_install.cmake 
rm -rf configfs/Makefile
rm -rf utlis/CMakeFiles
rm -rf utlis/cmake_install.cmake 
rm -rf utlis/Makefile